//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFSqlCe.Dal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CFSqlCe.Dal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 OH Vitamina D;20;60;20;60;ng/mL
        ///Acetilcolinesterase;7000;19000;7000;19000;U/L
        ///Acetona urina;0;50;0;50;mg/L
        ///Ácido fólico;3;19,7;3;19,7;ng/mL
        ///Ácido láctico;5,7;22;5,7;22;mg/dL
        ///Ácido úrico;3,4;7;2,4;5,7;mg/dL
        ///Ácidos graxos livres;0;0,72;0;0,72;mmol/L
        ///Albumina;3,5;5,2;3,5;5,2;g/dL
        ///Aldolase;0;7,6;0;7,6;U/L
        ///Aldosterona soro;1,8;23,2;1,8;23,2;ng/dL
        ///Alumínio ;0;10;0;10;µg/L
        ///Amilase soro;28;100;28;100;U/L
        ///Androstenediona;30;180;25;220;ng/dL
        ///Apolipoproteína A;90;170;107;214;mg/dL
        ///Apolipoproteína B;56 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exames {
            get {
                return ResourceManager.GetString("Exames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetilcolinesterase;Colinesterase
        ///Alumínio;Alumínio sangue
        ///Alumínio ;Alumínio plasma
        ///Cálcio;Cálcio soro
        ///Cálcio ionizado;Cálcio ionizável
        ///Cálcio ionizado;Cálcio iônico
        ///Calcitonina ;Calcitonina soro
        ///Capacidade de fixação de ferro ;TIBC
        ///Cobre;Cobre plasma
        ///Colesterol;Colesterol total
        ///Corticosterona;Composto B
        ///Creatinofosfoquinase;CPK
        ///Dehidroepiandrosterona;DHEA
        ///Dehidroepiandrosterona ;DHA
        ///Dehidrotestosterona;Dihidrotestosterona
        ///Dehidrotestosterona;DHT
        ///Desidrogenase Láctica;Lactato Desidrogenase  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sinonimos {
            get {
                return ResourceManager.GetString("Sinonimos", resourceCulture);
            }
        }
    }
}
